import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useDB } from "../lib/useDB";
import { db } from "../lib/db";
import { exportTransactionsCSV } from "../lib/csv";
import { clearClaudeKey, getClaudeKey, setClaudeKey } from "../lib/claude";
export default function Settings() {
    const state = useDB();
    const [key, setKey] = useState("");
    const [savedAt, setSavedAt] = useState(0);
    const hasKey = !!getClaudeKey();
    return (_jsxs("div", { className: "p-4 space-y-4", children: [_jsx("h1", { className: "text-xl font-semibold", children: "Settings" }), _jsxs("section", { className: "rounded-2xl bg-slate-900 p-3 space-y-2", children: [_jsx("h2", { className: "text-sm font-semibold", children: "Claude API key" }), _jsx("input", { type: "password", autoComplete: "off", spellCheck: false, value: key, onChange: (e) => setKey(e.target.value), placeholder: hasKey ? "•••••• (saved) " : "sk-ant-…", className: "w-full rounded-xl bg-slate-800 border border-slate-700 px-3 py-2 text-sm" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { disabled: !key.trim(), onClick: () => { setClaudeKey(key.trim()); setKey(""); setSavedAt(Date.now()); }, className: "flex-1 rounded-xl bg-sky-500 py-2 text-sm disabled:bg-slate-700", children: "Save to this device" }), hasKey && (_jsx("button", { onClick: () => { clearClaudeKey(); setSavedAt(Date.now()); }, className: "flex-1 rounded-xl bg-slate-700 py-2 text-sm", children: "Clear key" }))] }), _jsxs("p", { className: "text-xs text-slate-400", children: ["Key lives in this browser's localStorage. Never transmitted except directly to Anthropic. ", savedAt ? "Updated." : ""] }), _jsxs("label", { className: "flex items-center gap-2 text-sm pt-1", children: [_jsx("span", { className: "text-slate-400 flex-1", children: "Model" }), _jsx("input", { value: state.settings.claudeModel, onChange: (e) => db.setSettings({ claudeModel: e.target.value }), className: "rounded-lg bg-slate-800 border border-slate-700 px-2 py-1 text-sm w-56" })] })] }), _jsxs("section", { className: "rounded-2xl bg-slate-900 p-3 space-y-2", children: [_jsx("h2", { className: "text-sm font-semibold", children: "Portfolio" }), _jsxs("label", { className: "flex items-center gap-3", children: [_jsx("input", { type: "checkbox", checked: state.settings.allowOverdraft, onChange: (e) => db.setSettings({ allowOverdraft: e.target.checked }), className: "h-4 w-4" }), _jsx("span", { className: "text-sm", children: "Allow overdraft (cash can go negative)" })] }), _jsx("button", { onClick: () => exportTransactionsCSV(state.transactions), className: "w-full rounded-xl bg-slate-800 py-2 text-sm", children: "Export transactions (CSV)" }), _jsx("button", { onClick: () => {
                            if (confirm("Wipe all positions + transactions and reset cash to $1.15?")) {
                                db.reset();
                            }
                        }, className: "w-full rounded-xl bg-rose-600/70 py-2 text-sm", children: "Reset all data" })] }), _jsxs("section", { className: "text-xs text-slate-400 px-1", children: [_jsx("p", { children: "v0.1 \u00B7 PolyBot only simulates trades locally. No SMS, no auto-trading, no backend server. \u26A0\uFE0F Not financial advice." }), _jsxs("p", { children: ["Installed cash: ", _jsx("span", { className: "text-slate-200", children: state.settings.cashBalance }), " \u00B7 Positions: ", state.positions.length, " \u00B7 Transactions: ", state.transactions.length] })] })] }));
}
